Add arthur feature
Ulysseassoo/triumph pull request #2
Opened 2024-12-23 01:01 UTC by jabsraighs

2024-12-23 02:02 UTC, fabian222222 requested changes

2024-12-23 02:02 UTC, fabian222222 commented on src/application/usecases/piece/CreatePieceUseCase.ts
> +    console.log(this.pieceRepository)
console.log oublié

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/app.module.ts
> +        console.log('AppDataSource().options', AppDataSource().options);
console.log oublié

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/controllers/piece.controller.ts
> +    @Query('alertLimit') alertLimit?: number,
ça n'a pas vraiment de sens de pouvoir filtrer sur une alter limite je trouve

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/controllers/piece.controller.ts
> +
à partir du moment ou t'as la route findAll prenant en compte les filtres, je vois pas l'utilité des routes comme "name/:name"

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/order.repository.ts
> +      const query: Record<string, any> = {};
faut éviter tous les any et replacer par unknown si on sait vraiment pas

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/controllers/piece.controller.ts
> +
t'as deux fois la même fonction  pour update et patch

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/order.repository.ts
> +
t'as deux fois la même fonction update et update patch

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/order.repository.ts
> +
pareil si t'as déjà un find all avec les filtres, ces autres routes ne servent à rien

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/piece.repository.ts
> +
t'as déjà un find all filter, ça sert à rien les autres routes

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/piece.repository.ts
> +  }
si t'as déjà un find all filters, même le findAll tu peux l'enlever

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/piece.repository.ts
> +  }
parce que si tu laisses les champs vides dans findAllFilter, ça te get tout avec les paginations par défaut

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/repositories/piece.repository.ts
> +
t'as deux fois la fonction update

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/services/order.service.ts
> +
t'as deux fois la méthode, update et updatePatch

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/services/order.service.ts
> +
comme t'as le findAllFilters tu peux enlever celà

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/services/piece.service.ts
> +
t'as deux fois la méthode update et update patch

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/services/piece.service.ts
> +  }
pareil, comme t'as déjà un findallfilter, tu peux enlever le reste

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/dtos/order.dto.ts
> +  deliveryDate: string;
y'a pas date ? pour deliveryDate et orderDate

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/dtos/order.dto.ts
> +  totalAmount: number;
ourquoi on a cost et total amount ? c'est pas la même chose ?

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/nestjs/src/controllers/order.controller.ts
> +
t'as deux fois la fonction update et updatePatch

2024-12-23 02:02 UTC, fabian222222 commented on src/infrastructure/frameworks/express/package.json
> +    "express": "file:",
??

2024-12-23 13:24 UTC, jabsraighs commented on src/infrastructure/frameworks/express/package.json
> +    "express": "file:",
je sais pas pk je fais npm install ça me change comme ça c'est mon ide le pb je pense

2024-12-23 15:12 UTC, Ulysseassoo requested changes

2024-12-23 15:12 UTC, Ulysseassoo commented on package.json
> +    "clean-architecture": "file:",
Ca sert a quoi je ne comprends pas ? pourquoi c'est pas une dépendance qui est fetched ? Et tu l'utilises où ?

2024-12-23 15:12 UTC, Ulysseassoo commented on src/application/usecases/order/DeleteOrderUseCase.ts
> +    return success;
Le typage de la fonction ne correspond pas à la fonction. Si tu return l'objet delete change le "void"

2024-12-23 15:12 UTC, Ulysseassoo commented on src/infrastructure/database/entities/order.orm-entity.ts
> +  pieces: OrderPiece;
C'est pas censé être sous forme de JSON je crois. C'est une relation ManyToOne/OneToMany entre pièces et commandes.

2024-12-23 15:12 UTC, Ulysseassoo commented on src/infrastructure/database/entities/piece.orm-entity.ts
Rajouter la relation avec commande

2024-12-23 15:12 UTC, Ulysseassoo commented on src/infrastructure/database/entities/user.orm-entity.ts
Pourquoi y a autant de choses qui sont commentés ? Soit tu supprimes soit tu laisses

2024-12-23 15:12 UTC, Ulysseassoo commented on src/infrastructure/frameworks/Makefile
Le fichier makefile est-il nécessaire ? Première fois que je le vois

2024-12-23 15:12 UTC, Ulysseassoo commented on src/infrastructure/frameworks/docker-compose.yml
On utilise pas mongo donc il faudrait le retirer

2024-12-23 15:12 UTC, Ulysseassoo commented on src/infrastructure/orm/typeorm/data-source.ts
Laisser en test. En développement / prod on utilise postgresql. Quand on voudra faire du testing la on utilisera sqlite

2024-12-23 15:14 UTC, jabsraighs commented on package.json
> +    "clean-architecture": "file:",
je ne sais pas jai juste fais npm install

2024-12-23 15:17 UTC, Ulysseassoo commented on package.json
> +    "clean-architecture": "file:",
Ah c'est bizzare de ouf

2024-12-23 15:26 UTC, jabsraighs commented on src/application/usecases/order/DeleteOrderUseCase.ts
> +    return success;
await this.OrderRepository.delete(id); juste sans retour asyy  bv

2024-12-23 15:26 UTC, jabsraighs commented on src/infrastructure/database/entities/order.orm-entity.ts
> +  pieces: OrderPiece;
asy je vasi voir ça bv

2024-12-23 15:27 UTC, jabsraighs commented on src/infrastructure/frameworks/Makefile
c'est pour moi flmm de taper tt le temps docker compose up -d

2024-12-23 16:13 UTC, jabsraighs commented on src/infrastructure/frameworks/nestjs/src/dtos/order.dto.ts
> +  deliveryDate: string;
pb avec la bdd sqlite du coup je mets tecte pour que ça passe partt

2024-12-27 21:22 UTC, Ulysseassoo approved these changes

2024-12-27 21:24 UTC, fabian222222 approved these changes

2024-12-27 21:27 UTC, merged